# The workflow to check master after push.
name: Master checks after push
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'jdkfile'
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew build integrationTest
