# The workflow to check pull requests into master.
# This checks the source in the state as if after the merge.
name: Pull request checks
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build integrationTest
